### ISSUE TITLE
pre-built / undefined "type"

### ISSUE THREAD

**Issue by justrag** [tylerFowler/redux-remote-resource#3]
For a pretty standard CRA-generated app, webpackHotDevClient reports: 
> Critical dependencies:
1:492-499 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/redux-remote-resource/dist/redux-remote-resource.js 1:492-499

Also, the middleware seems to pass along the original type-less fetch-init-action, causing
> Uncaught Error: Actions may not have an undefined "type" property. Have you misspelled a constant?

errors in the following middlewares.

Am I doing something wrong?

**Comment by tylerFowler** [comment]
I'm not familiar with webpackHotDevClient but if it wants original sources you should be able to require the `lib/index.js` file specifically as long as your environment supports ES6 (with modules). 

As for the other question, I'm not quite sure what you mean by 'type-less', could you maybe post a snippet of how you're configuring the middleware and using it?

**Comment by justrag** [comment]
> you should be able to require the lib/index.js file

I can't get it to work neither by
`import remoteResourceMiddleware from 'redux-remote-resource/lib';`
nor by
`import remoteResourceMiddleware from 'redux-remote-resource/lib/index';`

> could you maybe post a snippet 

I've put up [an example](https://codesandbox.io/s/32L1oPVAO): a logger middleware (that goes in sequence after redux-remote-resource middleware) reports the original [RemoteResource] action - and it probably shouldn't. You can observe the "Actions may not have an undefined type property" error in the console.

Also, for some reason no lifecycle actions seem to dispatch?

**Comment by tylerFowler** [comment]
Ok I see what you mean by the types, I just realized that I didn't actually put this in the documentation anywhere but you do need the `redux-thunk` middleware installed in your store in order for it to work. Unfortunately that still gets the "no actions without a type" error in your example, and no API request is ever made so it's as if the middleware is never even running.. I'll look more into it tonight to see if I can recreate locally and dig a bit deeper. Though with your bit on having actions like `{ meta: "some meta string", [RemoteResource]: { ... } }`, that should be totally fine as long the `RemoteResource` symbol is a top level property of the dispatched action.

Also, with requiring the raw source you'll probably have to use a relative path like `import remoteResourceMiddleware from './node_modules/redux-remote-resource/lib';`.

**Comment by justrag** [comment]
> I just realized that I didn't actually put this in the documentation anywhere but you do need the redux-thunk middleware installed in your store in order for it to work.

Is there a way to declare it as an npm dependency?

> I'll look more into it tonight to see if I can recreate locally and dig a bit deeper.

Would strongly appreciate, this middleware looks very promising: standard FSAs with a built-in cache and callback on auth failure sounds really great.

> Though with your bit on having actions like { meta: "some meta string", [RemoteResource]: { ... } }, that should be totally fine as long the RemoteResource symbol is a top level property of the dispatched action.

The meta is not really needed there, I put it there only for identification purposes :)

> Also, with requiring the raw source you'll probably have to use a relative path like import remoteResourceMiddleware from './node_modules/redux-remote-resource/lib';.

Will try it and get back. From what I see, it's caused by currently-unsolved Webpack/CRA conflict:
https://github.com/webpack/webpack/issues/1617#issuecomment-279161234

**Comment by justrag** [comment]
`remoteResourceMiddleware from './node_modules/redux-remote-resource/lib';.`
is still DOA ('Module not found'). The same for:
`remoteResourceMiddleware from '../node_modules/redux-remote-resource/lib';.`
but as there's hope for eventual solution by CRA/Webpack teams, perhaps it's not worth any more bother for now.

I also tried adding ReduxThunk to the [example project](https://codesandbox.io/s/32L1oPVAO), but it doesn't seem to help.

**Comment by tylerFowler** [comment]
Sorry for the delay on this, my week got a bit busy. So I was right the middleware wasn't being called at all, turns out there was a bug in the logic behind whether or not it should process an action (checking for the special symbol). Which is bizarre because I use this in my own projects and have never run into this issue... But I've pushed an update (0.3.2) and your example does work with this updated version.

As for importing sources vs the built version, the package should now ship with the `lib/` directory, so that import should work now. And then also I've added usage with the `redux-thunk` middleware to the readme.

Closing for now but let me know if you run into more issues

**Comment by justrag** [comment]
Thanks, the dispatching works great now!
>bizarre because I use this in my own projects and have never run into this issue... 

Perhaps some changes in recent versions of redux (assuming you don't use the latest versions of Redux in your projects)?

I still can't get
`import remoteResourceMiddleware from 'redux-remote-resource/lib/';`
to work. It now generates
>Uncaught SyntaxError: Unexpected token import - index.js:8

which suggests for some reason it doesn't get transpiled?... Whatever, the regular `import` does work.

**Comment by tylerFowler** [comment]
Yeah.. with importing the sources directly it depends heavily on your build system so to troubleshoot that I'd have to see some of your build configuration, if it's worth it for you I'd be happy to make any adjustments in the source to increase compatibility.

**Comment by justrag** [comment]
The app is just a standard CRA-generated app, with no changes to webpack config whatsoever.
